#ifndef QTWEBSOCKETPROTOBUF_GLOBAL_H
#define QTWEBSOCKETPROTOBUF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTWEBSOCKETPROTOBUF_LIBRARY)
#define QTWEBSOCKETPROTOBUF_EXPORT Q_DECL_EXPORT
#else
#define QTWEBSOCKETPROTOBUF_EXPORT Q_DECL_IMPORT
#endif

#endif  // QTWEBSOCKETPROTOBUF_GLOBAL_H
